# Generated by Django 2.1.7 on 2019-03-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai4fitapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
