# Generated by Django 2.1.7 on 2019-03-10 18:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai4fitapp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_item_id', models.IntegerField(default=0)),
                ('workout_item_id', models.IntegerField(default=0)),
                ('workout_activity_result_id', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_item_id', models.IntegerField(default=0)),
                ('workout_item_id', models.IntegerField(default=0)),
                ('workout_activity_result_id', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('time', models.IntegerField(default=0)),
                ('isastart', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=0)),
                ('item_user_id', models.IntegerField(default=0)),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=0)),
                ('pausetime', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0.0)),
                ('avgspeed', models.FloatField(default=0.0)),
                ('maxspeed', models.FloatField(default=0.0)),
                ('minspeed', models.FloatField(default=0.0)),
                ('avgbpm', models.FloatField(default=0.0)),
                ('maxbpm', models.IntegerField(default=0)),
                ('minbpm', models.IntegerField(default=0)),
                ('avgaltitude', models.FloatField(default=0.0)),
                ('maxaltitude', models.FloatField(default=0.0)),
                ('minaltitude', models.FloatField(default=0.0)),
                ('calories', models.IntegerField(default=0)),
                ('isafitresult', models.IntegerField(default=0)),
                ('user_birthdate', models.DateField(default=datetime.datetime.today)),
                ('user_gender', models.CharField(max_length=1)),
                ('user_lastlogin', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_consent', models.IntegerField(default=0)),
                ('user_is_tester', models.IntegerField(default=0)),
                ('mark', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
            ],
        ),
    ]
