# Generated by Django 2.1.7 on 2019-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai4fitapp', '0005_auto_20190311_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutactivityresult',
            name='wactivity_comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workoutactivityresult',
            name='wactivity_label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workoutactivityresult',
            name='wactivity_type',
            field=models.CharField(max_length=255),
        ),
    ]
